<?php

return [
    'model' => [
        'address' => 'Address',
        'announcement' => 'Announcement',
        'attribute' => 'Attribute',
        'attribute_value' => 'Attribute value',
        'banner' => 'Banner',
        'blog' => 'Blog',
        'carrier' => 'Carrier',
        'cart' => 'Cart',
        'category' => 'Category',
        'category_group' => 'Category group',
        'category_sub_group' => 'Category sub-group',
        'config' => 'Settings',
        'coupon' => 'Coupon',
        'customer' => 'Customer',
        'currency' => 'Currency',
        'dispute' => 'Dispute',
        'email_template' => 'Email template',
        'faq' => 'Faq',
        'faqTopic' => 'FAQ topic',
        'gift_card' => 'Gift card',
        'inventory' => 'Inventory',
        'manufacturer' => 'Manufacturer',
        'merchant' => 'Merchant',
        'message' => 'Message',
        'notification' => 'Notification',
        'order' => 'Order',
        'packaging' => 'Packaging',
        'payment' => 'Payment',
        'payment_status' => 'Payment status',
        'payment_method' => 'Payment method',
        'page' => 'Page',
        'product' => 'Product',
        'refund' => 'Refund',
        'role' => 'Role',
        'shipping_rate' => 'Shipping rate',
        'shipping_zone' => 'Shipping zone',
        'shop' => 'Shop',
        'supplier' => 'Supplier',
        'slider' => 'Slider',
        'subscription_plan' => 'Subscription plan',
        'tax' => 'Tax',
        'ticket' => 'Ticket',
        'user' => 'User',
        'warehouse' => 'Warehouse',
    ]
];
