<?php
return [
	'access_token_required' => "Um token de acesso válido é necessário.",
    'auth_failed' => "Essas credenciais não correspondem aos nossos registros.",
	'auth_out' => "Logado com sucesso!",
	'auth_required' => "Faça login para acessar este conteúdo.",
    'cart_updated' => "Seu carrinho foi atualizado com sucesso.",
	'estimated_delivery_time' => "Tempo De Entrega Estimado: :tempo",
	'free_shipping' => "Frete Grátis",
	'item_added_to_wishlist' => "Item incluído na wishlist",
	'item_removed_from_wishlist' => "O item foi removido",
	'item_added_to_cart' => "Item adicionado ao carrinho",
	'item_alrealy_in_cart' => "Item alrealy em seu carrinho",
	'item_alrealy_in_wishlist' => "Item alrealy em sua wishlist",
	'item_max_stock' => "Este vendedor tem estoque limitado disponível",
	'item_minimum_qtt' => 'You can\'t place an order below this quantity',
	'item_not_in_stock' => 'We\'re sorry! This item not in stock',
	'item_alrealy_in_wishlist' => "Item alrealy em sua wishlist",
	'item_removed_from_cart' => "Item hs foi removido",
	'email_account_not_found' => 'We can\'t find a user with that e-mail address.',
    'password_reset_link_sent' => "O link de reset de senha enviado! Por favor, verifique seu e-mail.",
    'password_reset_token_404' => "Este token de reset de senha é inválido.",
    'password_reset_token_invalid' => "Este token de reset de senha é inválido.",
    'password_reset_successful' => "Sua senha foi atualizada com sucesso! Você pode fazer login agora.",
	'std_delivery_time' => "Tempo de entrega padrão",
	'you_already_gave_feedback' => "Você já deu o seu feedback!",
	'your_feedback_saved' => "Obrigado pelo seu feedback!",
	'invalid_request' => "Solicitação inválida!",
	'404' => "Este conteúdo não está disponível",
];