<?php
return [
    'invoice' => 'Fatura',
    'number'   => 'Referência',
    'date'     => 'Data de faturamento',
    'time'     => 'Tempo de faturamento',
    'due'      => 'Data de vencimento',
    'to'       => 'Faturamento para',
    'from'     => 'Faturamento de',
    'description'  => 'Descrição',
    'qty'      => 'Qtb',
    'price'    => 'Preço',
    'discount' => 'Desconto',
    'taxes'    => 'Impostos',
    'total'    => 'Total',
    'grand_total' => 'Grande Total',
    'handling' => 'Manipulação',
    'shipping' => 'Envio',
    'packaging' => 'Embalagem',
    'page'     => 'Página',
    'page_of'  => 'de',
    'message' => 'Mensagem',
    'footer_note' => 'Trata-se de uma fatura gerada por computador e que não requer assinatura.',
];
