<?php
return [
    /*
    |--------------------------------------------------------------------------
    | Navigation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the paginator library to build
    | the simple pagination links. You are free to change them to anything
    | you want to customize your views to better match your application.
    |
    */
    'dashboard' => 'Painel',
    'admin' => 'Admin',
    'announcements' => 'anúncios',
    'users' => 'Usuários',
    'customers' => 'Clientes',
    'currencies' => 'Moedas',
    'shops' => 'Lojas',
    'shipping_zones' => 'Zonas de navegação',
    'suppliers' => 'Fornecedores',
    'vendors' => 'Fornecedores',
    'merchants' => 'Comerciantes',
    'manufacturers' => 'Fabricantes',
    'blogs' => 'Blogs',
    'settings' => 'Configurações',
    'catalog' => 'Catálogo',
    'categories' => 'Categorias',
    'groups' => 'Grupos',
    'sub-groups' => 'Sub-grupos',
    'products' => 'Produtos',
    'attributes' => 'Atributos',
    'stock' => 'Estoque',
    'inventories' => 'Inventários',
    'warehouses' => 'Armazéns',
    'utilities' => 'Utilitários',
    'support' => 'Mesa de suporte',
    'support_messages' => 'Mensagens',
    'disputes' => 'Disputas',
    'support_tickets' => 'Ingressos',
    'refunds' => 'Reembolsos',
    'user_roles' => 'Funções do usuário',
    'taxes' => 'Impostos',
    'themes' => 'Temas',
    'theme_options' => 'Opções do tema',
    'banners' => 'Banners',
    'sliders' => 'Sliders',
    'shipping' => 'Envio',
    'packaging' => 'Embalagem',
    'carriers' => 'Transportadoras',
    'payment_methods' => 'Métodos de pagamento',
    'payment_statuses' => 'Status de pagamento',
    'email_templates' => 'Modelos de e-mail',
    'config' => 'Configuração',
    'general' => 'Configuração Geral',
    'orders' => 'Pedidos',
    'carts' => 'Carrinhos',
    'invoices' => 'Faturas',
    'payments' => 'Pagamentos',
    'promotions' => 'Promoções',
    'coupons' => 'Cupons',
    'gift_cards' => 'Cartões de presente',
    'faqs' => 'Faqs',
    'pages' => 'Páginas',
    'appearance' => 'Aparência',
    'performance' => 'Desempenho',
    'reports' => 'Relatórios',
    'visitors' => 'Visitantes',
    'sales_report' => 'Vendas',
    'system_settings' => 'Configurações do sistema',
    'subscription_plans' => 'Planos',
    // Version 1.4.0
    'chats' => 'chats',
    'countries' => 'Área de Negócios',
];