<?php

return [
	'access_token_required' => 'A valid access token is required. translated',
    'auth_failed' => 'These credentials do not match our records. translated',
	'auth_out' => 'Logged out successfully! translated',
	'auth_required' => 'Please login to access this content. translated',
    'cart_updated' => 'Your cart has been updated successfully. translated',
	'estimated_delivery_time' => 'Estimated Delivery Time: :time translated',
	'free_shipping' => 'Free Shipping translated',
	'item_added_to_wishlist' => 'Item added to wishlist translated',
	'item_removed_from_wishlist' => 'Item has been removed translated',
	'item_added_to_cart' => 'Item added to cart translated',
	'item_alrealy_in_cart' => 'Item alrealy in your cart translated',
	'item_alrealy_in_wishlist' => 'Item alrealy in your wishlist translated',
	'item_max_stock' => 'This seller has limited stock available translated',
	'item_minimum_qtt' => 'You can\'t place an order below this quantity translated',
	'item_not_in_stock' => 'We\'re sorry! This item not in stock translated',
	'item_alrealy_in_wishlist' => 'Item alrealy in your wishlist translated',
	'item_removed_from_cart' => 'Item hs been removed translated',
	'email_account_not_found' => 'We can\'t find a user with that e-mail address. translated',
    'password_reset_link_sent' => 'The password reset link sent! Please check your email. translated',
    'password_reset_token_404' => 'This password reset token is invalid. translated',
    'password_reset_token_invalid' => 'This password reset token is invalid. translated',
    'password_reset_successful' => 'Your password has been updated successfully! You can login now. translated',
	'std_delivery_time' => 'Standard delivery time translated',
	'you_already_gave_feedback' => 'You already gave your feedback! translated',
	'your_feedback_saved' => 'Thank you for your feedback! translated',
	'invalid_request' => 'Invalid request! translated',
	'404' => 'This content is not available translated',
];